{% set name = "mosestokenizer" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 438b3e35a221f7930c408e97e3f38af6d0cec74b991eb9edb00a44e3510e836d

build:
  number: 0
  noarch: python
  entry_points:
    - moses-tokenizer=mosestokenizer.tokenizer:main
    - moses-detokenizer=mosestokenizer.detokenizer:main
    - moses-punct-normalizer=mosestokenizer.punctnormalizer:main
    - moses-sent-splitter=mosestokenizer.sentsplitter:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - docopt
    - openfile
    - pip
    - python >=3.5
    - toolwrapper
  run:
    - docopt
    - openfile
    - python >=3.5
    - toolwrapper

test:
  imports:
    - mosestokenizer
  commands:
    - moses-tokenizer --help
    - moses-detokenizer --help
    - moses-punct-normalizer --help
    - moses-sent-splitter --help

about:
  home: https://bitbucket.org/luismsgomes/mosestokenizer
  license: GPL-2.0
  license_family: LGPL
  license_file: LICENSE
  summary: Wrappers for several pre-processing scripts from the Moses toolkit.
  doc_url: https://bitbucket.org/luismsgomes/mosestokenizer

extra:
  recipe-maintainers:
    - monaldoj
