travis:
  secure:
    BINSTAR_TOKEN: xbQg0y2ni/bcjXMy79lS2iucq+RiBB2EItN19UxOQenLNUaE5IWm+ZFy54eLvo3troX4hBwTbZI9XWr3Vai89DiiPan2i3yy4s8Y5O363Fl1TDFRH/l1pEriVcO2HLqccmbBtVlCuCxS0AHocESSasH7WBBFCCNjpq1NQ6MvvSGyWlXSJYI/y7uncduBoITUbQ/Lq/uhf0Z/sIwaUOdFCUX5Hm39qxwfiMNcC10KLOU++nz1/CkGSCPRPFe+KzGjmIwCHU7DH2i+iA0laJjp4xUbjLLRaKYRIIHVtLeGRO+FSzeScVY2D2oNabEt4SjIo/D8KBFSUIjkRzvQxwnH4aG7sfh7c9eInE0iMLLD2Dgoz12GI+Iu2NZ5/G08rVnELiTa54m6KxWpmC7l8zKKPMLKa3Qp5SWMFeQR0DUeaX8GTB7UoK2BOA9KkiZB4+pqeWzstUpC2/ZwqU2XraSlBl2QDbGqWEKOy3tkvgHij5H0l+WIk3fe82X6BBbi3VQM+AjNmziQyREnUUL7tnO9apkeM8A+bWVAt1NakbClCwonVAAQ6y/pGBSRGwG/h5E0dCx9uumQK4EiQV8PpYFXRuc0qN60J+4K4eKC0YQ2qfLEiQLTWR4VlWBSi0mWb+5pC3LmcSgw+TGMREMz45fQUCcqWxGZiHs4gowU3ZT0zPs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
