travis:
  secure:
    BINSTAR_TOKEN: GhZLNf8m4p263LngRlIQuJ69f8aA+yZO0L22ZcyfFnKZIfDWAI34MzWH+fRDRkZRbPwEilziCoVuNE53UyrQaKqsbtxnmz/Lr1pUqwKth7ruY0NhyeD7A67BpRAZt7hjNjLciR/W5zO6qqmOXRrCGcW0SyYt1CIWL5rtwi4t1i8fztuehrVam+gWzm1MNsxswpuz+s/3jHQjJ4+/4Ad1nYsdJ19mSL3OhUkTC18a+3adtFAO9WwdPd+Uz/7LfB93ZDsNX7K86UKHHwzr9Cp35V5YVoDhnA7qIvSe0SwJ6Nhu6eVHFJg8hGJx1NJPW5yrvD8VVEUaibWtPVQ9yzE3PH8836MBZv0M9m8JnILiwLyNnwjpLxtuWwSlxtr62f/AXWdB25OaUWdcV6DUWJiVPQH1PLbkM5fErWTgzTb/RiK2NW/Ra8ZbBEFkBhnVAXBELE3DVjXMCKYf8GCfXAprOICXqDqniiimK83+kZ9yA5HUhsGHjy9IdC6pHisJ1xEZf9A3G8N4magxIba2XfW75VYiAQTuB/+UZTS6nmxT1SC5LjfTkZlYICBAdnTb5HQr10z6in6ITRbanK93Dqqii9ot3KGvAsB1baF22WQs/9nJzTZGiN3e8s5Qy3FijslzAf81JYMqS5jjKtNfop101s3YLec6dryp/NYs4CQrhms=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
